name: Deploy WordPress to AKS
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest #  
    env:
      ACR_NAME: "wpfinalregistry" # 
      IMAGE_NAME: "custom-wordpress"
      RESOURCE_GROUP: "wp-final-project-rg"
      AKS_CLUSTER: "wp-aks-cluster-final"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 

      - name: Azure Login
        uses: azure/login@v2 
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3 
      - name: Terraform Init and Plan
        run: |
          cd terraform-infra
          terraform init
          terraform plan

      - name: Login to ACR
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build and Push Image
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Set Up Cluster
        run: az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER }}

      - name: Deploy to AKS
        run: |
          sed -i "s|image: wordpress:latest|image: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}|g" k8s/wordpress-deployment.yml
          kubectl apply -f k8s/secrets.yml
          kubectl apply -f k8s/wordpress-deployment.yml
          kubectl apply -f k8s/wordpress-service.yml